# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Imagemage < Formula
  desc "A focused CLI tool for generating and editing images with Google's Gemini API without the bloat"
  homepage "https://github.com/quinnypig/imagemage"
  version "0.1.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/quinnypig/imagemage/releases/download/v0.1.12/imagemage_0.1.12_Darwin_x86_64.tar.gz"
      sha256 "9649e651efe8b1735cda00f2fc1646a5ca231a8655308df54ab8904def096052"

      define_method(:install) do
        bin.install "imagemage"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/quinnypig/imagemage/releases/download/v0.1.12/imagemage_0.1.12_Darwin_arm64.tar.gz"
      sha256 "c33deeb6ed7ef4b670febb2736c8203be302745852a5ffabb32a97e5f7e9c749"

      define_method(:install) do
        bin.install "imagemage"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/quinnypig/imagemage/releases/download/v0.1.12/imagemage_0.1.12_Linux_x86_64.tar.gz"
      sha256 "ea0d8142482977264efdefa9d5a352eca7233774c5882e851e229837485223ec"
      define_method(:install) do
        bin.install "imagemage"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/quinnypig/imagemage/releases/download/v0.1.12/imagemage_0.1.12_Linux_arm64.tar.gz"
      sha256 "0947f7cdee74a1f82dfd816b364fa7132d0980f10867b72397fde3fe7b5e82d7"
      define_method(:install) do
        bin.install "imagemage"
      end
    end
  end

  test do
    system "#{bin}/imagemage", "--version"
  end
end
