# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Imagemage < Formula
  desc "A tiny CLI for bossing around OpenAI Images and Gemini without installing someone's KPI farm"
  homepage "https://github.com/quinnypig/imagemage"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/quinnypig/imagemage/releases/download/v0.2.0/imagemage_0.2.0_Darwin_x86_64.tar.gz"
      sha256 "baa1869c6244f50fd5d6ff514696c56f20f1f1494b5b7c5b2e2828cd7e112296"

      define_method(:install) do
        bin.install "imagemage"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/quinnypig/imagemage/releases/download/v0.2.0/imagemage_0.2.0_Darwin_arm64.tar.gz"
      sha256 "fbdeb3f6cc910e129a1f9f179046dddebaed5d10404b54799b7822f843fe0438"

      define_method(:install) do
        bin.install "imagemage"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/quinnypig/imagemage/releases/download/v0.2.0/imagemage_0.2.0_Linux_x86_64.tar.gz"
      sha256 "1c215a568c8cb72a825b00859f53e476cdca100696421dd815d82b54b5a74f45"
      define_method(:install) do
        bin.install "imagemage"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/quinnypig/imagemage/releases/download/v0.2.0/imagemage_0.2.0_Linux_arm64.tar.gz"
      sha256 "62fe2cc29bddcfb922e892c2263105bf31ac09b26979da5be12eadabc2867086"
      define_method(:install) do
        bin.install "imagemage"
      end
    end
  end

  test do
    system "#{bin}/imagemage", "--version"
  end
end
