# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Imagemage < Formula
  desc "A tiny CLI for bossing around OpenAI Images and Gemini without installing someone's KPI farm"
  homepage "https://github.com/quinnypig/imagemage"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/quinnypig/imagemage/releases/download/v0.2.1/imagemage_0.2.1_Darwin_x86_64.tar.gz"
      sha256 "0a5ea16279cd4df79a9b06417cbc48e2b539459df4660a0fc4357db216c28f4f"

      define_method(:install) do
        bin.install "imagemage"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/quinnypig/imagemage/releases/download/v0.2.1/imagemage_0.2.1_Darwin_arm64.tar.gz"
      sha256 "3bf757031f4e75efe613b809e8223540d588a89333bb4383c7e76d3c58edc982"

      define_method(:install) do
        bin.install "imagemage"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/quinnypig/imagemage/releases/download/v0.2.1/imagemage_0.2.1_Linux_x86_64.tar.gz"
      sha256 "6af9e3ce186b9a2b6d9755c75579dcfaffec54738ff475cceaa045706a3c74ea"
      define_method(:install) do
        bin.install "imagemage"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/quinnypig/imagemage/releases/download/v0.2.1/imagemage_0.2.1_Linux_arm64.tar.gz"
      sha256 "b7b659aa2d939d6c41f6461d39cefaaf8b5ebed2ecff0f86e32bf0d90118bc80"
      define_method(:install) do
        bin.install "imagemage"
      end
    end
  end

  test do
    system "#{bin}/imagemage", "--version"
  end
end
